name: automerge
on:
  pull_request:
    types:
      - opened
      - labeled
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: verify label is auto-pr
        uses: actions/verify-pr-label-action@v1.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "auto-pr"
      - name: automerge
        uses: "pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
