on:
  push:
    branches:
      - "master"
    tags:
      - "*"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "master"
          destination_branch: "release/staging"
          pr_title: "Pulling master into release/staging with version ${{ github.ref }}"
          pr_body: ":crown: *An automated PR*" # Full markdown support, requires pr_title to be set
          pr_reviewer: "kjuulh" # Comma-separated list (no spaces)
          pr_assignee: "kjuulh" # Comma-separated list (no spaces)
          pr_label: "auto-pr" # Comma-separated list (no spaces)
          github_token: ${{ secrets.GITHUB_TOKEN }}
